# -- Site Configuration --

baseURL = "https://draksec.cz/"
theme = "congo"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 15
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
