languageCode = "en-US"
languageName = "English (USA)"
languageDirection = "ltr"
weight = 1

title = "Drak's infosec blog"
copyright = "&copy; 2023 Draksec"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "Drak's personal information security blog"

[params.author]
  name = "Drak's personal information security blog"
  headline = "Honza"
  links = [
    { circle-info = "/about" },
    { email = "mailto:dr4k.sec{at}gmail.com" },
    { discord = "https://discord.com/users/308273436076015618" },
    { github = "https://github.com/draktuls" },
  ]